#!/bin/bash
# Configure openSUSE

printf "Current hostname: "
echo $(hostname)
read -p 'Would you like to rename this computer? openSUSE ships with hostname=NA. [y/n]' RENAME

if [[ "$RENAME" == "y" ]]; then
	read -p 'What new name would you like to use? ' SWEET_NAME_HERE
	sudo hostnamectl set-hostname $SWEET_NAME_HERE
fi

read -p 'Install all standard productivity software? [y/n] ' INSTALL
read -p 'Install Miniconda and QIIME 2? [y/n] ' QIIME
read -p 'Clone all of your github repos? [y/n] ' SCRAPE_GH
read -p 'Configure Terminal, bash, git, and vim? [y/n] ' CONFIG
read -p 'Add mint background images and filter out the bad ones? [y/n]' BGROUND

if [[ "$INSTALL" == "y" ]]; then
	# install packman and codecs for video applications. required for vlc install in suseInstalls.sh
	bash ~/src/jiggety/videoCodecs.sh
	bash ~/src/jiggety/suseInstalls.sh
fi

if [[ "$QIIME" == "y" ]]; then
	bash ~/src/jiggety/qiimeInstall.sh
fi

if [[ "$SCRAPE_GH" == "y" ]]; then
	read -p "Have you already configured an SSH Key and API Token for github? [y/n] " KEYS
	if [[ "$KEYS" == "n" ]]; then
		bash ~/src/jiggety/generateKeys.sh
	fi
	bash ~/src/jiggety/cloneAll.sh

	if [[ "$KEYS" == "n" ]]; then
	        rm ~/src/jiggety/scrpt_vars
	fi
fi

if [[ "$CONFIG" == "y" ]]; then
	# Configure GNOME desktop (sounds, bluetooth, etc)
	bash ~/src/jiggety/gnomeConfig.sh
	
	# Overwrite Gnome Terminal defaults
	bash ~/src/jiggety/terminalconfig.sh

	# back up .bashrc
	cp ~/.bashrc ~/.bashrc_old

	# TODO: edit .bashrc PS1 variable to display git branch

#	Conda appears to set a git prompt by default now:
#	sed -i 's/($debian_chroot)}/($debian_chroot)}$(__git_ps1 "(%s)")/g' ~/.bashrc

	# symlink bash_aliases and source them in .bash_rc
	# NOTE: must be non-root
	if [ -f ~/.bash_aliases ]; then
	  echo ".bash_aliases already exists. backing it up at .bash_aliases_old"
	  mv ~/.bash_aliases ~/.bash_aliases_old
	fi
	ln -s ~/src/jiggety/dotfiles/aliases ~/.bash_aliases
	printf '\n# added by jiggety:\n' >> ~/.bashrc
	printf '%s\n    %s\n%s\n' 'if [ -f ~/.bash_aliases ]; then' 'source ~/.bash_aliases' 'fi' >> ~/.bashrc

	# symlink git aliases
	if [ -f ~/.gitconfig ]; then
	  echo ".gitconfig already exists. backing it up at .gitconfig_old"
	  mv ~/.gitconfig ~/.gitconfig_old
	fi
	ln -s ~/src/jiggety/dotfiles/gitconfig ~/.gitconfig

	# Write NeoVim config to "nvimrc"
	mkdir ~/.config/nvim
	cat ~/src/jiggety/dotfiles/init.vim >> ~/.config/nvim/init.vim
	read -p "Open nvim and type :VundleInstall. [Enter to continue] " DUMMY

	# symlink vscode settings and keybinds to jiggety
	read -p "Overwrite VSCode settings and keybinds with dotfiles? [y/n]' VSCODE
	if [[ "$VSCODE" == "y" ]]; then
	  cp ~/.config/Code/User/settings.json ~/.config/Code/User/settings_bkp.json
	  ln -sf ~/src/jiggety/dotfiles/vsc_settings.json ~/.config/Code/User/settings.json

	  cp ~/.config/Code/User/keybindings.json ~/.config/Code/User/keybindings_bkp.json
	  ln -sf ~/src/jiggety/dotfiles/vsc_keybindings.json ~/.config/Code/User/keybindings.json
	fi
fi

if [[ "$BGROUND" == "y" ]]; then
	bash ~/src/jiggety/backgroundSlideshow.sh
fi

