#!/bin/bash
# Configure linuxMint - backups, workspaces, tiling, hot corners, icons on panel

# Create src directory
if [ -d ~/src ]; then
  printf '** WARNING: This system already has a ~/src directory. **\n'
  printf 'It may have been configured already. Continuing may break stuff. '
  printf 'Are you sure you want to continue? [y/n]'
  read CONTINUE
  if [ $CONTINUE != 'y' ]; then
    return
  fi
else
  mkdir ~/src
fi


# Install MiniConda, QIIME2, Atom, Atom Packages, flake8, git
# clone common QIIME repos, add relevant git remotes
# Install R and relevant packages (ggplot2, dplyr, etc)
# Install firefox, fb-blocker plugin, chrome

# edit .bashrc PS1 variable to display git branch
sed -i 's/chroot)}$/chroot)}$(__git_ps1 "(%s)")/g' ~/.bashrc

## Add aliases to .bashrc
# TODO Do I need to CHMOD jiggety for security reasons?
# NOTE: must be non-root
# create .bash_aliases file and write aliases
if [ ! -f ~/.bash_aliases ]; then
  cat ~/src/jiggety/aliases >> ~/.bash_aliases
fi

# append .bash_aliases call to .bashrc
printf '\n# added by jiggety:\n' >> ~/.bashrc
printf '%s\n    %s\n%s\n' 'if [ -f ~/.bash_aliases ]; then' 'source ~/.bash_aliases' 'fi' >> ~/.bashrc

# Configure printers?


